uniform sampler2D iTexture0;
uniform sampler2D iTexture1;
uniform float iFracScale;
uniform float iFracAng1;
uniform float iFracAng2;
uniform vec3 iFracShift;
uniform vec3 iFracCol;
uniform vec3 iMarblePos;
uniform float iMarbleRad;
uniform float iFlagScale;
uniform vec3 iFlagPos;
uniform int FRACTAL_ITER;
uniform int MARBLE_MODE;
uniform float time;
uniform int iFrame;
uniform float PBR_METALLIC;
uniform float PBR_ROUGHNESS;
uniform vec3 BACKGROUND_COLOR;
uniform vec3 LIGHT_DIRECTION;
uniform vec3 LIGHT_COLOR;
uniform bool SHADOWS_ENABLED; 
uniform float gamma_material;
uniform float gamma_sky;
uniform float gamma_camera;
uniform bool FRACTAL_GLOW;
uniform bool FLAG_GLOW;

struct glcamera
{
	vec3 position;
	vec3 dirx;
	vec3 diry;
	vec3 dirz;
	vec2 resolution;
	float aspect_ratio;
	float FOV;
	float focus;
	float bokeh;
	float exposure;
	float mblur;
	float speckle;
	float size;
	float bloomintensity;
	float bloomradius;
	bool cross_eye;
	float eye_separation;
};

uniform glcamera Camera;
uniform glcamera PrevCamera;